workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal
  GLOBAL_CMAKE_OPTIONS: -DSACN_BUILD_TESTS=ON -DSACN_BUILD_EXAMPLES=ON

windows-build:
  stage: build
  tags:
    - ct-windows
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 16 2019" -A x64 $env:GLOBAL_CMAKE_OPTIONS ..
    - cmake --build . --config Release -j
    - ctest -C Release --output-on-failure
  artifacts:
    when: always
    reports:
      junit: build/tests/unit/test-results/*.xml

macos-build:
  stage: build
  tags:
    - ct-macos
  script:
    - mkdir build
    - cd build
    - cmake ${GLOBAL_CMAKE_OPTIONS} ..
    - cmake --build .
    - ctest --output-on-failure
  artifacts:
    when: always
    reports:
      junit: build/tests/unit/test-results/*.xml

linux-build:
  stage: build
  tags:
    - etc-linux-docker
  image: etc-docker.artifactory-mid.etcconnect.com/etc/common-tech/gcc-cmake:latest
  variables:
    CMAKE_ASAN_DEFINITIONS: -DCMAKE_C_FLAGS="-fsanitize=address" -DCMAKE_CXX_FLAGS="-fsanitize=address" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"
  script:
    - mkdir build
    - cd build
    - cmake ${GLOBAL_CMAKE_OPTIONS} ${CMAKE_ASAN_DEFINITIONS} ..
    - cmake --build .
    - ctest --output-on-failure
  artifacts:
    when: always
    reports:
      junit: build/tests/unit/test-results/*.xml

docs-test:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - etc-linux-docker
  image: etc-docker.artifactory-mid.etcconnect.com/etc/common-tech/doxygen:1.9.1
  script:
    - pip install --upgrade etclibtool
    - etclibtool docs -c tools/ci/etclibtool_config.json --warn-as-error . 1.9.1

deploy-docs:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  tags:
    - etc-linux-docker
  image: etc-docker.artifactory-mid.etcconnect.com/etc/common-tech/doxygen:1.9.1
  variables:
    GH_REPO_NAME: sACNDocs
    GH_REPO_REF: github.com/ETCLabs/sACNDocs.git
    GH_REPO_TOKEN: $SVC_ETCLABS_REPO_TOKEN
  script:
    - pip install --upgrade etclibtool
    - chmod +x tools/ci/publish_docs.sh
    - tools/ci/publish_docs.sh

include:
  - project: 'etc/common-tech/tools/gitlab-ci-util'
    ref: v1.4.0
    file: '/ci-yml/deploy-versioned-build.yml'
